<?php
require_once '../include.php';
checkLogined();
$act=$_REQUEST['act'];
$id=$_REQUEST['id'];
if($act=="logout"){
    logout();
}elseif($act=="addAdmin"){
    $mes=addAdmin();
}elseif($act=="editAdmin"){
    $mes=editAdmin($id);
}elseif($act=="delAdmin"){
    delAdmin($id);
}elseif($act=="addCate"){
    $mes=addCate();
}elseif($act=="editCate"){
    $mes=editCate($id);
}elseif($act=="delCate"){
    $mes=delCate($id);
}elseif($act=="addPro"){
    $mes=addPro();
}elseif($act=="editPro"){
    $mes=editPro($id);
}elseif($act=="delPro"){
    $mes=delPro($id);
}elseif($act=="addUser"){
    $mes=addUser();
}elseif($act=="editUser"){
    $mes=editUser($id);
}elseif($act=="delUser"){
    delUser($id);
}elseif($act=="waterText"){
    $mes=doWaterText($id);
}elseif($act=="waterPic"){
    $mes=doWaterPic($id);
}
?>
<!DOCTYPE html>
<html>
<head>
<title>Insert title here</title>
</head>
<body>
<?php
	if($mes){
        echo $mes;
    }
?>
</body>
</html>
